public enum PatternID
{
    NOMALATTACK,
    HEAVYATTACK,
    RANGEATTACK,
    STUNATTACK,
    AIRBORNEATTACK,
    TELEPORT,
    TRIPLEATTACK,
    COMBOATTACK,
    BLOWATTACK,
    SPECALATTACK,
    RUSH,
    DASH
}